USE [master]
GO

/****** Object:  Database [ProductCatalogDB]    Script Date: 2/13/2024 10:46:01 AM ******/
CREATE DATABASE [ProductCatalogDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProductCatalogDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ProductCatalogDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProductCatalogDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ProductCatalogDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProductCatalogDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProductCatalogDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProductCatalogDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProductCatalogDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProductCatalogDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProductCatalogDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProductCatalogDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProductCatalogDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProductCatalogDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProductCatalogDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProductCatalogDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProductCatalogDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProductCatalogDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProductCatalogDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProductCatalogDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProductCatalogDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProductCatalogDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProductCatalogDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProductCatalogDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProductCatalogDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProductCatalogDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProductCatalogDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProductCatalogDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProductCatalogDB] SET RECOVERY FULL 
GO

ALTER DATABASE [ProductCatalogDB] SET  MULTI_USER 
GO

ALTER DATABASE [ProductCatalogDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProductCatalogDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProductCatalogDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProductCatalogDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ProductCatalogDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProductCatalogDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ProductCatalogDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ProductCatalogDB] SET  READ_WRITE 
GO


USE [ProductCatalogDB]
GO

/****** Object:  Table [dbo].[Products]    Script Date: 2/13/2024 10:46:34 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Products](
	[productId] [int] IDENTITY(1,1) NOT NULL,
	[nameProduct] [nvarchar](255) NOT NULL,
	[shortDescriptionProduct] [nvarchar](500) NOT NULL,
	[categoryProduct] [nvarchar](100) NOT NULL,
	[productImage] [varbinary](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[productId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO




